# Generated by Django 4.1.7 on 2023-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0003_alter_postmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
